/*using System;
using Microsoft.Xna.Framework;
using Terraria;
using Terraria.Graphics.Effects;
using Terraria.Graphics.Shaders;
using Terraria.ID;
using Terraria.ModLoader;
using Terraria.Localization;

namespace opswordsII.Items.Lanzables
{
	public class LlaveInglesa: ModItem
	{
		public override void SetStaticDefaults()
		{
	  	DisplayName.SetDefault("Wrench");
            DisplayName.AddTranslation(GameCulture.FromCultureName(GameCulture.CultureName.French), "Clé");
            DisplayName.AddTranslation(GameCulture.FromCultureName(GameCulture.CultureName.Spanish), "Llave Inglesa");
		}

		 public override void SetStaticDefaults()
		{ 
	            Item.damage = 30;           //this is the item damage
            Item.thrown = true;             //this make the item do throwing damage
            Item.noMelee = true;
            Item.width = 20;
            Item.height = 20;
            Item.useTime = 30;       //this is how fast you use the item
            Item.useAnimation = 30;   //this is how fast the animation when the item is used
            Item.useStyle = 1;      
            Item.knockBack = 6;
            Item.value = 25000;
            Item.rare = 2;
            Item.reuseDelay = 20;    //this is the item delay
            Item.UseSound = SoundID.Item18;
            Item.autoReuse = true;
	          Item.shoot = 582;
         Item.shootSpeed = 18f;     //projectile speed
            Item.useTurn = true;
            Item.maxStack = 1;       //this is the max stack of this item
            Item.consumable = false;  //this make the item consumable when used
            Item.noUseGraphic = true;


	    }
	}
}*/
