using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace RemnantOfTheAncientsMod.Common.Prefix
{
    internal class PrefixID
    {
        public const short Large = 1;
        public const short Massive = 2;
        public const short Dangerous = 3;
        public const short Savage = 4;
        public const short Sharp = 5;
        public const short Pointy = 6;
        public const short Tiny = 7;
        public const short Terrible = 8;
        public const short Small = 9;
        public const short Dull = 10;
        public const short Unhappy = 11;
        public const short Bulky = 12;
        public const short Shameful = 13;
        public const short Heavy = 14;
        public const short Light = 15;
        public const short Sighted = 16;
        public const short Rapid = 17;
        public const short Hasty = 18;
        public const short Intimidating = 19;
        public const short DeadlyRangedWeapons = 20;
        public const short Staunch = 21;
        public const short Awful = 22;
        public const short Lethargic = 23;
        public const short Awkward = 24;
        public const short Powerful = 25;
        public const short Mystic = 26;
        public const short Adept = 27;
        public const short Masterful = 28;
        public const short Inept = 29;
        public const short Ignorant = 30;
        public const short Deranged = 31;
        public const short Intense = 32;
        public const short Taboo = 33;
        public const short Celestial = 34;
        public const short Furious = 35;
        public const short Keen = 36;
        public const short Superior = 37;
        public const short Forceful = 38;
        public const short Broken = 39;
        public const short Damaged = 40;
        public const short Shoddy = 41;
        public const short Quick = 42;
        public const short Deadly = 43;
        public const short Agile = 44;
        public const short Nimble = 45;
        public const short Murderous = 46;
        public const short Slow = 47;
        public const short Sluggish = 48;
        public const short Lazy = 49;
        public const short Annoying = 50;
        public const short Nasty = 51;
        public const short Manic = 52;
        public const short Hurtful = 53;
        public const short Strong = 54;
        public const short Unpleasant = 55;
        public const short Weak = 56;
        public const short Ruthless = 57;
        public const short Frenzying = 58;
        public const short Godly = 59;
        public const short Demonic = 60;
        public const short Zealous = 61;
        public const short Hard = 62;
        public const short Guarding = 63;
        public const short Armored = 64;
        public const short Warding = 65;
        public const short Arcane = 66;
        public const short Precise = 67;
        public const short Lucky = 68;
        public const short Jagged = 69;
        public const short Spiked = 70;
        public const short Angry = 71;
        public const short Menacing = 72;
        public const short Brisk = 73;
        public const short Fleeting = 74;
        public const short Hasty1 = 75;
        public const short Quick1 = 76;
        public const short Wild = 77;
        public const short Rash = 78;
        public const short Intrepid = 79;
        public const short Violent = 80;
        public const short Legendary = 81;
        public const short Unreal = 82;
        public const short Mythical = 83;
        public const short LegendaryTerrarianVariant = 84;
    }
}
