using RemnantOfTheAncientsMod.Content.Items.Consumables.Pociones.Models;
using System;
using Terraria;
using Terraria.ID;

namespace RemnantOfTheAncientsMod.Content.Items.Consumables.Pociones
{
    public class EndlessGravitation : BasePotions
    {
        public override Item ItemBase => new(ItemID.GravitationPotion);
        public override char GramaticalCorrection => 'F';
    }

    public class EndlessHeaRtreach : BasePotions
    {
        public override Item ItemBase => new(ItemID.HeartreachPotion);
        public override char GramaticalCorrection => 'F';
    }
    public class EndlessInferno : BasePotions
    {
        public override Item ItemBase => new(ItemID.InfernoPotion);
        public override char GramaticalCorrection => 'F';
    }
    public class EndlessIronSkin : BasePotions
    {
        public override Item ItemBase => new(ItemID.IronskinPotion);

        public override char GramaticalCorrection => 'F';
    }
    public class EndlessAmmoReservation : BasePotions
    {
        public override Item ItemBase => new(ItemID.AmmoReservationPotion);

        public override char GramaticalCorrection => 'F';
    }
    public class EndlessArchery : BasePotions
    {
        public override Item ItemBase => new(ItemID.ArcheryPotion); 
        public override char GramaticalCorrection => 'F';
    }
    public class EndlessBuilder : BasePotions
    {
        public override Item ItemBase => new(ItemID.BuilderPotion);
        public override char GramaticalCorrection => 'F';
    }
    public class EndlessCalming : BasePotions
    {
        public override Item ItemBase => new(ItemID.CalmingPotion);
        public override char GramaticalCorrection => 'F';
    }
    public class EndlessCrate : BasePotions
    {
        public override Item ItemBase => new(ItemID.CratePotion);
        public override char GramaticalCorrection => 'F';
    }
    public class EndlessDangersense : BasePotions
    {
        public override Item ItemBase => new(ItemID.TrapsightPotion);
        public override char GramaticalCorrection => 'F';
    }
    public class EndlessFishing : BasePotions
    {
        public override Item ItemBase => new(ItemID.FishingPotion);
        public override char GramaticalCorrection => 'F';
    }
    public class EndlessRegeneration : BasePotions
    {
        public override Item ItemBase => new(ItemID.RegenerationPotion); 
        public override char GramaticalCorrection => 'F';
    }

    public class EndlessSonar : BasePotions
    {
        public override Item ItemBase => new(ItemID.SonarPotion); 
        public override char GramaticalCorrection => 'F';
    }

    public class EndlessSpelunker : BasePotions
    {
        public override Item ItemBase => new(ItemID.SpelunkerPotion);
        public override char GramaticalCorrection => 'F';
    }

    public class EndlessSummoning : BasePotions
    {
        public override Item ItemBase => new(ItemID.SummoningPotion);

        public override char GramaticalCorrection => 'F';
    }

    public class EndlessSwiftness : BasePotions
    {
        public override Item ItemBase => new(ItemID.SwiftnessPotion);
        public override char GramaticalCorrection => 'F';
    }
    public class EndlessThorns : BasePotions
    {
        public override Item ItemBase => new(ItemID.ThornsPotion); 
        public override char GramaticalCorrection => 'F';
    }
    public class EndlessBattle : BasePotions
    {
        public override Item ItemBase => new(ItemID.BattlePotion);

        public override char GramaticalCorrection => 'F';
    }
    public class EndlessEndurance : BasePotions
    {
        public override Item ItemBase => new(ItemID.EndurancePotion);
        public override char GramaticalCorrection => 'F';
    }

    public class EndlessFeather : BasePotions
    {
        public override Item ItemBase => new(ItemID.FeatherfallPotion);
        public override char GramaticalCorrection => 'F';
    }
    public class EndlessGills : BasePotions
    {
        public override Item ItemBase => new(ItemID.GillsPotion);
        public override char GramaticalCorrection => 'F';
    }
    public class EndlessFlipper : BasePotions
    {
        public override Item ItemBase => new(ItemID.FlipperPotion);
        public override char GramaticalCorrection => 'F';
    }
    public class EndlessWaterWalking : BasePotions
    {
        public override Item ItemBase => new(ItemID.WaterWalkingPotion);
        public override char GramaticalCorrection => 'F';
    }
    public class EndlessHunter : BasePotions
    {
        public override Item ItemBase => new(ItemID.HunterPotion);
        public override char GramaticalCorrection => 'F';
    }
    public class EndlessInvisibility : BasePotions
    {
        public override Item ItemBase => new(ItemID.InvisibilityPotion);
        public override char GramaticalCorrection => 'F';
    }

    public class EndlessLifeForce : BasePotions
    {
        public override Item ItemBase => new(ItemID.LifeforcePotion);

        public override char GramaticalCorrection => 'F';
    }

    public class EndlessMining : BasePotions
    {
        public override Item ItemBase => new(ItemID.MiningPotion);
        public override char GramaticalCorrection => 'F';
    }

    public class EndlessManaPower : BasePotions
    {
        public override Item ItemBase => new(ItemID.MagicPowerPotion);
        public override char GramaticalCorrection => 'F';
    }

    public class EndlessManaRegeneration : BasePotions
    {
        public override Item ItemBase => new(ItemID.ManaRegenerationPotion);
        public override char GramaticalCorrection => 'F';
    }
    public class EndlessNightOwl : BasePotions
    {
        public override Item ItemBase => new(ItemID.NightOwlPotion);

        public override char GramaticalCorrection => 'F';
    }
    public class EndlessObsidian : BasePotions
    {
        public override Item ItemBase => new(ItemID.ObsidianSkinPotion);

        public override char GramaticalCorrection => 'F';
    }
    public class EndlessRage : BasePotions
    {
        public override Item ItemBase => new(ItemID.RagePotion);
        public override char GramaticalCorrection => 'F';
    }
    public class EndlessShine : BasePotions
    {
        public override Item ItemBase => new(ItemID.ShinePotion);
        public override char GramaticalCorrection => 'F';
    }
    public class EndlessTitan : BasePotions
    {
        public override Item ItemBase => new(ItemID.TitanPotion);
        public override char GramaticalCorrection => 'F';
    }
    public class EndlessWarmth : BasePotions
    {
        public override Item ItemBase => new(ItemID.WarmthPotion);
        public override char GramaticalCorrection => 'F';
    }
    public class EndlessWrath : BasePotions
    {
        public override Item ItemBase => new(ItemID.WrathPotion);
        public override char GramaticalCorrection => 'F';
    }
    public class EndlessLeasserLuck : BasePotions
    {
        public override Item ItemBase => new(ItemID.LuckPotionLesser);
        public override char GramaticalCorrection => 'F';
    }
    public class EndlessLuck : BasePotions
    {
        public override Item ItemBase => new(ItemID.LuckPotion);
        public override char GramaticalCorrection => 'F';
    }
    public class EndlessGreaterLuck : BasePotions
    {
        public override Item ItemBase => new(ItemID.LuckPotionGreater);

        public override char GramaticalCorrection => 'F';
    }
    public class EndlessWormHole : BasePotions
    {
        public override Item ItemBase => new(ItemID.WormholePotion);
        public override char GramaticalCorrection => 'F';
    }
    public class EndlessStink : BasePotions
    {
        public override Item ItemBase => new(ItemID.StinkPotion);
        public override char GramaticalCorrection => 'F';
    }
    public class EndlessLove : BasePotions
    {
        public override Item ItemBase => new(ItemID.LovePotion);
        public override char GramaticalCorrection => 'F';
    }
    public class EndlessBiomeSightPotion : BasePotions
    {
        public override Item ItemBase => new(ItemID.BiomeSightPotion);

        public override char GramaticalCorrection => 'F';
    }
}
