using RemnantOfTheAncientsMod.Content.Items.Consumables.Pociones.Models;
using Terraria;
using Terraria.ID;

namespace RemnantOfTheAncientsMod.Content.Items.Consumables.Pociones
{
    public class EndlessGravitation : BasePotions
    {
        public override Item ItemBase => new(ItemID.GravitationPotion);
    }

    public class EndlessHeaRtreach : BasePotions
    {
        public override Item ItemBase => new(ItemID.HeartreachPotion);
    }
    public class EndlessInferno : BasePotions
    {
        public override Item ItemBase => new(ItemID.InfernoPotion);
    }
    public class EndlessIronSkin : BasePotions
    {
        public override Item ItemBase => new(ItemID.IronskinPotion);
    }
    public class EndlessAmmoReservation : BasePotions
    {
        public override Item ItemBase => new(ItemID.AmmoReservationPotion);
    }
    public class EndlessArchery : BasePotions
    {
        public override Item ItemBase => new(ItemID.ArcheryPotion);
    }
    public class EndlessBuilder : BasePotions
    {
        public override Item ItemBase => new(ItemID.BuilderPotion);
    }
    public class EndlessCalming : BasePotions
    {
        public override Item ItemBase => new(ItemID.CalmingPotion);
    }
    public class EndlessCrate : BasePotions
    {
        public override Item ItemBase => new(ItemID.CratePotion);
    }
    public class EndlessDangersense : BasePotions
    {
        public override Item ItemBase => new(ItemID.TrapsightPotion);
    }
    public class EndlessFishing : BasePotions
    {
        public override Item ItemBase => new(ItemID.FishingPotion);
    }
    public class EndlessRegeneration : BasePotions
    {
        public override Item ItemBase => new(ItemID.RegenerationPotion);
    }

    public class EndlessSonar : BasePotions
    {
        public override Item ItemBase => new(ItemID.SonarPotion);
    }

    public class EndlessSpelunker : BasePotions
    {
        public override Item ItemBase => new(ItemID.SpelunkerPotion);
    }

    public class EndlessSummoning : BasePotions
    {
        public override Item ItemBase => new(ItemID.SummoningPotion);
    }

    public class EndlessSwiftness : BasePotions
    {
        public override Item ItemBase => new(ItemID.SwiftnessPotion);
    }
    public class EndlessThorns : BasePotions
    {
        public override Item ItemBase => new(ItemID.ThornsPotion);
    }
    public class EndlessBattle : BasePotions
    {
        public override Item ItemBase => new(ItemID.BattlePotion);
    }
    public class EndlessEndurance : BasePotions
    {
        public override Item ItemBase => new(ItemID.EndurancePotion);
    }

    public class EndlessFeather : BasePotions
    {
        public override Item ItemBase => new(ItemID.FeatherfallPotion);
    }
    public class EndlessGills : BasePotions
    {
        public override Item ItemBase => new(ItemID.GillsPotion);
    }
    public class EndlessFlipper : BasePotions
    {
        public override Item ItemBase => new(ItemID.FlipperPotion);
    }
    public class EndlessWaterWalking : BasePotions
    {
        public override Item ItemBase => new(ItemID.WaterWalkingPotion);
    }
    public class EndlessHunter : BasePotions
    {
        public override Item ItemBase => new(ItemID.HunterPotion);
    }
    public class EndlessInvisibility : BasePotions
    {
        public override Item ItemBase => new(ItemID.InvisibilityPotion);
    }

    public class EndlessLifeForce : BasePotions
    {
        public override Item ItemBase => new(ItemID.LifeforcePotion);
    }

    public class EndlessMining : BasePotions
    {
        public override Item ItemBase => new(ItemID.MiningPotion);
    }

    public class EndlessManaPower : BasePotions
    {
        public override Item ItemBase => new(ItemID.MagicPowerPotion);
    }

    public class EndlessManaRegeneration : BasePotions
    {
        public override Item ItemBase => new(ItemID.ManaRegenerationPotion);
    }
    public class EndlessNightOwl : BasePotions
    {
        public override Item ItemBase => new(ItemID.NightOwlPotion);
    }
    public class EndlessObsidian : BasePotions
    {
        public override Item ItemBase => new(ItemID.ObsidianSkinPotion);
    }
    public class EndlessRage : BasePotions
    {
        public override Item ItemBase => new(ItemID.RagePotion);
    }
    public class EndlessShine : BasePotions
    {
        public override Item ItemBase => new(ItemID.ShinePotion);
    }
    public class EndlessTitan : BasePotions
    {
        public override Item ItemBase => new(ItemID.TitanPotion);
    }
    public class EndlessWarmth : BasePotions
    {
        public override Item ItemBase => new(ItemID.WarmthPotion);
    }
    public class EndlessWrath : BasePotions
    {
        public override Item ItemBase => new(ItemID.WrathPotion);
    }
    public class EndlessLeasserLuck : BasePotions
    {
        public override Item ItemBase => new(ItemID.LuckPotionLesser);
    }
    public class EndlessLuck : BasePotions
    {
        public override Item ItemBase => new(ItemID.LuckPotion);
    }
    public class EndlessGreaterLuck : BasePotions
    {
        public override Item ItemBase => new(ItemID.LuckPotionGreater);
    }
    public class EndlessWormHole : BasePotions
    {
        public override Item ItemBase => new(ItemID.WormholePotion);
    }
    public class EndlessStink : BasePotions
    {
        public override Item ItemBase => new(ItemID.StinkPotion);
    }
    public class EndlessLove : BasePotions
    {
        public override Item ItemBase => new(ItemID.LovePotion);
    }
    public class EndlessBiomeSightPotion : BasePotions
    {
        public override Item ItemBase => new(ItemID.BiomeSightPotion);
    }
}
