using Terraria;
using Terraria.ID;
using Terraria.Localization;

namespace RemnantOfTheAncientsMod.Content.Items.Consumables.Pociones
{
    public class EndlessGravitation : BasePotions
    {
        public override Item ItemBase => new(ItemID.GravitationPotion);
        public override void SetStaticDefaults()
        {
           // //DisplayName.SetDefault("Endless Gravitation Potion");
           // //DisplayName.AddTranslation(GameCulture.FromCultureName(GameCulture.CultureName.Spanish), "Poción de gravedad eterna");
        }
    }
    public class EndlessHeaRtreach : BasePotions
    {
        public override Item ItemBase => new(ItemID.HeartreachPotion);
        public override void SetStaticDefaults()
        {
           // //DisplayName.SetDefault("Endless Heartreach Potion");
           // //DisplayName.AddTranslation(GameCulture.FromCultureName(GameCulture.CultureName.Spanish), "Poción de alcanzacorazón eterna");
        }
    }
    public class EndlessInferno : BasePotions
    {
        public override Item ItemBase => new(ItemID.InfernoPotion);
        public override void SetStaticDefaults()
        {
           // //DisplayName.SetDefault("Endless Inferno Potion");
           // //DisplayName.AddTranslation(GameCulture.FromCultureName(GameCulture.CultureName.Spanish), "Poción del infierno eterna");
        }
    }
    public class EndlessIronSkin : BasePotions
    {
        public override Item ItemBase => new(ItemID.IronskinPotion);
        public override void SetStaticDefaults()
        {
           // //DisplayName.SetDefault("Endless Ironskin Potion");
           // //DisplayName.AddTranslation(GameCulture.FromCultureName(GameCulture.CultureName.Spanish), "Poción de piel de hierro eterna");
        }
    }
    public class EndlessAmmoReservation : BasePotions
    {
        public override Item ItemBase => new(ItemID.AmmoReservationPotion);
        public override void SetStaticDefaults()
        {
           // //DisplayName.SetDefault("Endless Ammo Reservation Potion");
           // //DisplayName.AddTranslation(GameCulture.FromCultureName(GameCulture.CultureName.Spanish), "Poción de munición eterna");
        }
    }
    public class EndlessArchery : BasePotions
    {
        public override Item ItemBase => new(ItemID.ArcheryPotion);
        public override void SetStaticDefaults()
        {
           // //DisplayName.SetDefault("Endless Archery Potion");
           // //DisplayName.AddTranslation(GameCulture.FromCultureName(GameCulture.CultureName.Spanish), "Poción de arquero eterna");
        }
    }
    public class EndlessBuilder : BasePotions
    {
        public override Item ItemBase => new(ItemID.BuilderPotion);
        public override void SetStaticDefaults()
        {
           // //DisplayName.SetDefault("Endless Builder Potion");
           // //DisplayName.AddTranslation(GameCulture.FromCultureName(GameCulture.CultureName.Spanish), "Poción constructora eterna");
        }
    }
    public class EndlessCalming : BasePotions
    {
        public override Item ItemBase => new(ItemID.CalmingPotion);
        public override void SetStaticDefaults()
        {
           // //DisplayName.SetDefault("Endless Calming Potion");
           // //DisplayName.AddTranslation(GameCulture.FromCultureName(GameCulture.CultureName.Spanish), "Poción tranquilizadora eterna");
        }
    }
    public class EndlessCrate : BasePotions
    {
        public override Item ItemBase => new(ItemID.CratePotion);
        public override void SetStaticDefaults()
        {
           // //DisplayName.SetDefault("Endless Crate Potion");
           // //DisplayName.AddTranslation(GameCulture.FromCultureName(GameCulture.CultureName.Spanish), "Poción de caja eterna");

        }
    }
    public class EndlessDangersense : BasePotions
    {
        public override Item ItemBase => new(ItemID.TrapsightPotion);
        public override void SetStaticDefaults()
        {
           // //DisplayName.SetDefault("Endless Dangersense Potion");
           // //DisplayName.AddTranslation(GameCulture.FromCultureName(GameCulture.CultureName.Spanish), "Poción de sentido del peligro eterna");

        }
    }
    public class EndlessFishing : BasePotions
    {
        public override Item ItemBase => new(ItemID.FishingPotion);
        public override void SetStaticDefaults()
        {
           // //DisplayName.SetDefault("Endless Fishing Potion");
           // //DisplayName.AddTranslation(GameCulture.FromCultureName(GameCulture.CultureName.Spanish), "Poción de pesca eterna");
        }
    }
    public class EndlessRegeneration : BasePotions
    {
        public override Item ItemBase => new(ItemID.RegenerationPotion);
        public override void SetStaticDefaults()
        {
           // //DisplayName.SetDefault("Endless Regeneration Potion");
           // //DisplayName.AddTranslation(GameCulture.FromCultureName(GameCulture.CultureName.Spanish), "Poción de regeneración eterna");
        }
    }

    public class EndlessSonar : BasePotions
    {
        public override Item ItemBase => new(ItemID.SonarPotion);
        public override void SetStaticDefaults()
        {
           // //DisplayName.SetDefault("Endless Sonar Potion");
           // //DisplayName.AddTranslation(GameCulture.FromCultureName(GameCulture.CultureName.Spanish), "Poción de sonar eterna");
        }
    }

    public class EndlessSpelunker : BasePotions
    {
        public override Item ItemBase => new(ItemID.SpelunkerPotion);
        public override void SetStaticDefaults()
        {
           // //DisplayName.SetDefault("Endless Spelunker Potion");
           // //DisplayName.AddTranslation(GameCulture.FromCultureName(GameCulture.CultureName.Spanish), "Poción de espeleógo eterna");
        }
    }

    public class EndlessSummoning : BasePotions
    {
        public override Item ItemBase => new(ItemID.SummoningPotion);
        public override void SetStaticDefaults()
        {
           // //DisplayName.SetDefault("Endless Summoning Potion");
           // //DisplayName.AddTranslation(GameCulture.FromCultureName(GameCulture.CultureName.Spanish), "Poción de invocación eterna");
        }
    }

    public class EndlessSwiftness : BasePotions
    {
        public override Item ItemBase => new(ItemID.SwiftnessPotion);
        public override void SetStaticDefaults()
        {
           // //DisplayName.SetDefault("Endless Swiftness Potion");
           // //DisplayName.AddTranslation(GameCulture.FromCultureName(GameCulture.CultureName.Spanish), "Poción de rapidez eterna");
        }
    }
    public class EndlessThorns : BasePotions
    {
        public override Item ItemBase => new(ItemID.ThornsPotion);
        public override void SetStaticDefaults()
        {
           // //DisplayName.SetDefault("Endless Thorns Potion");
           // //DisplayName.AddTranslation(GameCulture.FromCultureName(GameCulture.CultureName.Spanish), "Poción de espinas eterna");
        }
    }
    public class EndlessBattle : BasePotions
    {
        public override Item ItemBase => new(ItemID.BattlePotion);
        public override void SetStaticDefaults()
        {
           // //DisplayName.SetDefault("Endless Battle Potion");
           // //DisplayName.AddTranslation(GameCulture.FromCultureName(GameCulture.CultureName.Spanish), "Poción de batalla eterna");
        }
    }
    public class EndlessEndurance : BasePotions
    {
        public override Item ItemBase => new(ItemID.EndurancePotion);
        public override void SetStaticDefaults()
        {
           // //DisplayName.SetDefault("Endless Endurance Potion");
           // //DisplayName.AddTranslation(GameCulture.FromCultureName(GameCulture.CultureName.Spanish), "Poción de resistencia eterna");
        }
    }

    public class EndlessFeather : BasePotions
    {
        public override Item ItemBase => new(ItemID.FeatherfallPotion);
        public override void SetStaticDefaults()
        {
           // //DisplayName.SetDefault("Endless Featherfall Potion");
           // //DisplayName.AddTranslation(GameCulture.FromCultureName(GameCulture.CultureName.Spanish), "Poción de caída de pluma eterna");
        }
    }
    public class EndlessGills : BasePotions
    {
        public override Item ItemBase => new(ItemID.GillsPotion);
        public override void SetStaticDefaults()
        {
           // //DisplayName.SetDefault("Endless Gills Potion");
           // //DisplayName.AddTranslation(GameCulture.FromCultureName(GameCulture.CultureName.Spanish), "Poción de agallas eterna");
        }
    }
    public class EndlessFlipper : BasePotions
    {
        public override Item ItemBase => new(ItemID.FlipperPotion);
        public override void SetStaticDefaults()
        {
           // //DisplayName.SetDefault("Endless Flipper Potion");
           // //DisplayName.AddTranslation(GameCulture.FromCultureName(GameCulture.CultureName.Spanish), "Poción de fltación eterna");
        }
    }
    public class EndlessWaterWalking : BasePotions
    {
        public override Item ItemBase => new(ItemID.WaterWalkingPotion);
        public override void SetStaticDefaults()
        {
           // //DisplayName.SetDefault("Endless Water Walking Potion");
           // //DisplayName.AddTranslation(GameCulture.FromCultureName(GameCulture.CultureName.Spanish), "Poción de caminar sobre el agua eterna");
        }
    }
    public class EndlessHunter : BasePotions
    {
        public override Item ItemBase => new(ItemID.HunterPotion);
        public override void SetStaticDefaults()
        {
           // //DisplayName.SetDefault("Endless Hunter Potion");
           // //DisplayName.AddTranslation(GameCulture.FromCultureName(GameCulture.CultureName.Spanish), "Poción de cazador eterna");
        }
    }
    public class EndlessInvisibility : BasePotions
    {
        public override Item ItemBase => new(ItemID.InvisibilityPotion);
        public override void SetStaticDefaults()
        {
           // //DisplayName.SetDefault("Endless Invisibility Potion");
           // //DisplayName.AddTranslation(GameCulture.FromCultureName(GameCulture.CultureName.Spanish), "Poción de invisibilidad eterna");
        }
    }

    public class EndlessLifeForce : BasePotions
    {
        public override Item ItemBase => new(ItemID.LifeforcePotion);
        public override void SetStaticDefaults()
        {
           // //DisplayName.SetDefault("Endless Lifeforce Potion");
           // //DisplayName.AddTranslation(GameCulture.FromCultureName(GameCulture.CultureName.Spanish), "Poción de fuerza vital eterna");
        }
    }

    public class EndlessMining : BasePotions
    {
        public override Item ItemBase => new(ItemID.MiningPotion);
        public override void SetStaticDefaults()
        {
           // //DisplayName.SetDefault("Endless Mining Potion");
           // //DisplayName.AddTranslation(GameCulture.FromCultureName(GameCulture.CultureName.Spanish), "Poción de minería eterna");
        }
    }

    public class EndlessManaPower : BasePotions
    {
        public override Item ItemBase => new(ItemID.MagicPowerPotion);
        public override void SetStaticDefaults()
        {
           // //DisplayName.SetDefault("Endless Magic Power Potion");
           // //DisplayName.AddTranslation(GameCulture.FromCultureName(GameCulture.CultureName.Spanish), "Poción de poder mágico eterna");
        }
    }

    public class EndlessManaRegeneration : BasePotions
    {
        public override Item ItemBase => new(ItemID.ManaRegenerationPotion);
        public override void SetStaticDefaults()
        {
           // //DisplayName.SetDefault("Endless Magic Regeneration Potion");
           // //DisplayName.AddTranslation(GameCulture.FromCultureName(GameCulture.CultureName.Spanish), "Poción reg. de maná eterna");
        }
    }
    public class EndlessNightOwl : BasePotions
    {
        public override Item ItemBase => new(ItemID.NightOwlPotion);
        public override void SetStaticDefaults()
        {
           // //DisplayName.SetDefault("Endless Night Owl Potion");
           // //DisplayName.AddTranslation(GameCulture.FromCultureName(GameCulture.CultureName.Spanish), "Poción de noctámbulo eterna");
        }
    }
    public class EndlessObsidian : BasePotions
    {
        public override Item ItemBase => new(ItemID.ObsidianSkinPotion);
        public override void SetStaticDefaults()
        {
           // //DisplayName.SetDefault("Endless Obsidian Skin Potion");
           // //DisplayName.AddTranslation(GameCulture.FromCultureName(GameCulture.CultureName.Spanish), "Poción de piel de obsidiana eterna");
        }
    }
    public class EndlessRage : BasePotions
    {
        public override Item ItemBase => new(ItemID.RagePotion);
        public override void SetStaticDefaults()
        {
           // //DisplayName.SetDefault("Endless Rage Potion");
           // //DisplayName.AddTranslation(GameCulture.FromCultureName(GameCulture.CultureName.Spanish), "Poción de furia eterna");
        }
    }
    public class EndlessShine : BasePotions
    {
        public override Item ItemBase => new(ItemID.ShinePotion);
        public override void SetStaticDefaults()
        {
           // //DisplayName.SetDefault("Endless Shine Potion");
           // //DisplayName.AddTranslation(GameCulture.FromCultureName(GameCulture.CultureName.Spanish), "Poción de brillo eterna");
        }
    }
    public class EndlessTitan : BasePotions
    {
        public override Item ItemBase => new(ItemID.TitanPotion);
        public override void SetStaticDefaults()
        {
           // //DisplayName.SetDefault("Endless Titan Potion");
           // //DisplayName.AddTranslation(GameCulture.FromCultureName(GameCulture.CultureName.Spanish), "Poción de titán eterna");
        }
    }
    public class EndlessWarmth : BasePotions
    {
        public override Item ItemBase => new(ItemID.WarmthPotion);
        public override void SetStaticDefaults()
        {
           // //DisplayName.SetDefault("Endless Warmth Potion");
           // //DisplayName.AddTranslation(GameCulture.FromCultureName(GameCulture.CultureName.Spanish), "Poción del calor eterna");
        }
    }
    public class EndlessWrath : BasePotions
    {
        public override Item ItemBase => new(ItemID.WrathPotion);
        public override void SetStaticDefaults()
        {
           // //DisplayName.SetDefault("Endless Wrath Potion");
           // //DisplayName.AddTranslation(GameCulture.FromCultureName(GameCulture.CultureName.Spanish), "Poción de ira eterna");
        }
    }
    public class EndlessLeasserLuck : BasePotions
    {
        public override Item ItemBase => new(ItemID.LuckPotionLesser);
        public override void SetStaticDefaults()
        {
           // //DisplayName.SetDefault("Endless Lesser Luck Potion");
           // //DisplayName.AddTranslation(GameCulture.FromCultureName(GameCulture.CultureName.Spanish), "Poción de suerte menor eterna");
        }
    }
    public class EndlessLuck : BasePotions
    {
        public override Item ItemBase => new(ItemID.LuckPotion);
        public override void SetStaticDefaults()
        {
           // //DisplayName.SetDefault("Endless Luck Potion");
           // //DisplayName.AddTranslation(GameCulture.FromCultureName(GameCulture.CultureName.Spanish), "Poción de suerte eterna");
        }
    }
    public class EndlessGreaterLuck : BasePotions
    {
        public override Item ItemBase => new(ItemID.LuckPotionGreater);
        public override void SetStaticDefaults()
        {
           // //DisplayName.SetDefault("Endless Greater Luck Potion");
           // //DisplayName.AddTranslation(GameCulture.FromCultureName(GameCulture.CultureName.Spanish), "Poción de suerte grande eterna");
        }
    }
    public class EndlessWormHole : BasePotions
    {
        public override Item ItemBase => new(ItemID.WormholePotion);
        public override void SetStaticDefaults()
        {
           // //DisplayName.SetDefault("Endless Wormhole Potion");
           // //DisplayName.AddTranslation(GameCulture.FromCultureName(GameCulture.CultureName.Spanish), "Poción de agujero de gusano eterna");

        }
    }
    public class EndlessStink : BasePotions
    {
        public override Item ItemBase => new(ItemID.StinkPotion);
        public override void SetStaticDefaults()
        {
           // //DisplayName.SetDefault("Endless Stink Potion");
           // //DisplayName.AddTranslation(GameCulture.FromCultureName(GameCulture.CultureName.Spanish), "Poción apestoza eterna");

        }
    }
    public class EndlessLove : BasePotions
    {
        public override Item ItemBase => new(ItemID.LovePotion);
        public override void SetStaticDefaults()
        {
           // //DisplayName.SetDefault("Endless Love Potion");
           // //DisplayName.AddTranslation(GameCulture.FromCultureName(GameCulture.CultureName.Spanish), "Poción de de amor eterna");

        }
    }
}
