//using FargowiltasSouls.Core.Globals;
//using FargowiltasSouls.Core.NPCMatching;
//using FargowiltasSouls.Core.Systems;
//using Microsoft.Xna.Framework.Graphics;
//using ReLogic.Content;
//using Terraria;
//using Terraria.ModLoader;

//namespace RemnantOfTheAncientsMod.Common.ModCompativilitie.Fargos
//{
//    [ExtendsFromMod("FargowiltasSouls")]
//    //public class FargosOverride : EModeNPCBehaviour
//    //{
//        //public override NPCMatcher CreateMatcher()
//        //{
//        //    throw new System.NotImplementedException();
//        //}
//        //public override GlobalNPC NewInstance(NPC target)
//        //{
//        //    OverrideTryLoadSprites(target);
//        //    return base.NewInstance(target);
//        //}
//        //public void OverrideTryLoadSprites(NPC npc)
//        //{
//        //    if (!Main.dedServ)
//        //    {
//        //        bool recolor =  WorldSavingSystem.EternityMode;
//        //        if (recolor)
//        //        {
//        //            LoadSprites(npc, recolor);
//        //        }
//        //    }
//        //}
//        //protected static Asset<Texture2D> OverrideLoadSprite(bool recolor, string texture)
//        //{
//        //    if (ModContent.RequestIfExists("FargowiltasSouls/Assets/ExtraTextures/" + (recolor ? "Resprites/" : "Vanilla/") + texture, out Asset<Texture2D> asset, AssetRequestMode.ImmediateLoad))
//        //    {
//        //        return asset;
//        //    }

//        //    return null;
//        //}
//   // }
//}
